apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: shopnow
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://sankarrajsundaram_db_user:oDcVStsNAbhKjbLL@mongo-cluster.k49gd3a.mongodb.net/?appName=mongo-cluster"